sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get update  -qq -y
  - sudo apt-get install -qq -y debootstrap
  - sudo apt-get install -qq -y debian-keyring debian-archive-keyring
  - if [ ! -e /usr/share/debootstrap/scripts/ascii ]; then sudo ln -s /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/ascii; fi
  - if [ ! -e /usr/share/debootstrap/scripts/beowulf ]; then sudo ln -s /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/beowulf; fi
matrix:
  include:
    - name: 'Devuan 1 - jessie'
      env: DISTNAME=jessie
    - name: 'Devuan 2 - ascii'
      env: DISTNAME=ascii
    - name: 'Devuan 3 - beowulf'
      env: DISTNAME=beowulf
script:
  - echo "$DOCKER_PASSWORD" | docker login -u darkgigabyte --password-stdin
  - set +e
  - set -v
  - ./build.sh -v -t 'Europe/Berlin' -u darkgigabyte -p -d $DISTNAME
